version: '3'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '@Vxhung2k'
      MYSQL_DATABASE: server-db
      MYSQL_USER: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
  app:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER= root
      - DB_PASSWORD= '@Vxhung2k'
      - DB_DATABASE= server-db
volumes:
  db-data:
